add build instructions to readme, and move other docs into doc/

diff --git a/bin/install-cmake b/bin/install-cmake
--- a/bin/install-cmake
+++ b/bin/install-cmake
@@ -8,13 +8,23 @@ if [ "$(uname)" != Linux ]; then
     exit 1
 fi
 
-if ! >/dev/null command -v wget; then
-    >&2 echo 'This installer requires wget.'
-    exit 2
+VERSION=3.24.2
+REPO=$(dirname "$0")/..
+
+# If a suitably recent version of cmake is already installed, then don't bother.
+if >/dev/null command -v cmake && >/dev/null 2>&1 cmake -P "$REPO/CheckRequiredCMakeVersion.cmake"; then
+    echo 'A suitable version of cmake is already installed.'
+    exit
 fi
 
+for required in wget sed; do
+    if ! >/dev/null command -v "$required"; then
+        >&2 echo "This installer requires $required."
+        exit 2
+    fi
+done
+
 ARCHITECTURE=$(uname -m)
-VERSION=3.24.2
 INSTALLER=cmake-${VERSION}-linux-${ARCHITECTURE}.sh
 URL=https://github.com/Kitware/CMake/releases/download/v${VERSION}/${INSTALLER}
 
